name: Generate pacman animation

on:
  schedule:
    # Her 12 saatte bir (UTC 00:00–00:59 ve 12:00–12:59 aralığında her dakika)
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman SVG(s)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: aysecetin
          # Bazı sürümlerde default olarak dist/ içine yazar.
          # Eğer başka yere yazıyorsa (örn. outputDir) parametresi varsa "dist" yap.

      - name: Push dist/ to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
